{% set name = "idq" %}
{% set version = "0.6.5" %}
{% set sha256 = "aec83710fbf43202ea0fdd9dde6de4ae41981be8f3ea6f34ac460d484d8f8dd9" %}

{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - dqsegdb2 >=1.0
    - ezdag >=0.4
    - gpstime
    - gwpy >=2.1
    - gwtrigfind
    - h5py >=2.2.1
    - igwn-segments >=2.0
    - ligo-scald >=0.8
    - matplotlib-base >=2.0
    - numpy >=1.7.1
    - pluggy
    - python >={{ python_min }}
    - python-confluent-kafka
    - python-lal
    - python-ldas-tools-framecpp
    - python-ligo-lw
    - scikit-learn >=0.18.2
    - scipy >=0.12.1
    - toml
    - ujson
    - xgboost

test:
  requires:
    - python {{ python_min }}
  imports:
    - idq
  commands:
    - idq-batch --help
    - idq-calibrate --help
    - idq-check_config --help
    - idq-condor_batch --help
    - idq-create-channel-list --help
    - idq-evaluate --help
    - idq-generate-vetoes --help
    - idq-simtimeseries --help
    - idq-stream --help
    - idq-streaming_train --help
    - idq-streaming_evaluate --help
    - idq-streaming_calibrate --help
    - idq-streaming_timeseries --help
    - idq-streaming_report --help
    - idq-target-times --help
    - idq-timeseries --help
    - idq-train --help
    - idq-report --help

about:
  home: https://git.ligo.org/lscsoft/iDQ
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://lscsoft.docs.ligo.org/iDQ
  dev_url: https://git.ligo.org/lscsoft/iDQ
  summary: a low-latency statistical data quality pipeline for glitch detection

extra:
  recipe-maintainers:
    - nothisisolivia
    - myNameIsPatrick
