{% set name = "iDQ" %}
{% set version = "0.2.0" %}
{% set sha256 = "13cc433f5c161e1fae2b8abe7628963826c39a2365000253b5111407ae32767c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python <3
    - pip
    - setuptools

  run:
    - python <3
    - numpy >=1.7.1
    - scipy
    - h5py >=2.3.0
    - matplotlib >=1.2.0
    - python-lal
    - python-lalframe
    - lscsoft-glue
    - ligo-common
    - ligo-segments
    - ligo-scald
    - libframe
    - dqsegdb
    - python-ldas-tools-framecpp
    - python-confluent-kafka >=0.11.4
    - scikit-learn >=0.18.2

test:
  imports:
    - idq

about:
  home: https://git.ligo.org/reed.essick/iDQ
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.ligo.org/reed.essick/iDQ
  dev_url: https://git.ligo.org/reed.essick/iDQ
  summary: a low-latency statistical data quality pipeline for glitch detection

extra:
  recipe-maintainers:
    -  myNameIsPatrick
