{% set name = "iDQ" %}
{% set version = "0.3.1" %}
{% set sha256 = "3efd56556e2a4e335887fc9d2cd96c7e884240bcc869fec45146cfa0cdb528c9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - dqsegdb
    - h5py >=2.3.0
    - lscsoft-glue
    - ligo-common
    - ligo-segments
    - ligo-scald
    - libframe
    - matplotlib-base >=1.2.0
    - numpy >=1.7.1
    - python
    - python-confluent-kafka >=0.11.4
    - python-lal
    - python-lalframe
    - python-ldas-tools-framecpp
    - python-ligo-lw
    - scikit-learn >=0.18.2
    - scipy

test:
  imports:
    - idq
  commands:
    - idq-batch --help
    - idq-calibrate --help
    - idq-condor_batch --help
    - idq-condor_train --help
    - idq-condor_evaluate --help
    - idq-condor_calibrate --help
    - idq-condor_timeseries --help
    - idq-check_config --help
    - idq-evaluate --help
    #- idq-kwm2hdf5 --help  <-- requires gstlal (not a user script)
    - idq-kwm2kws --help
    - idq-monitor --help
    - idq-report --help
    - idq-simtimeseries --help
    - idq-stream --help
    - idq-streaming_train --help
    - idq-streaming_evaluate --help
    - idq-streaming_calibrate --help
    - idq-streaming_timeseries --help
    - idq-streaming_report --help
    - idq-target-times --help
    - idq-timeseries --help
    - idq-train --help

about:
  home: "https://git.ligo.org/reed.essick/iDQ"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  doc_url: "https://docs.ligo.org/reed.essick/iDQ"
  dev_url: "https://git.ligo.org/reed.essick/iDQ"
  summary: "a low-latency statistical data quality pipeline for glitch detection"

extra:
  recipe-maintainers:
    -  myNameIsPatrick
