travis:
  secure:
    BINSTAR_TOKEN: WrSWEH2g8ke7RMGXTh2ksopNYFU3NaMIrVqduzahS6/waOcB5MaYA78DnkXoPk+sCYO+tBV87H7CFZMrrqLVxe8NHM7V44uH38QF+ysWCHhwZ8V4+HCKKoMSCZlUczlYXJVUXqB4QQZ1HztzkIVQm58xsl17NM1qRxi5dnHCutG3xVo0558riDSWwErsaarwRzZg8t8Hgtq9KTXVf1Yr7Bh6i2VN8JosjhDmsv9y5o9JKSF5Ya7Hpc/Yg/u6es7ZMm7CGiaI1TvW/aT7oCRj26aUf0vn5Uztr4Wv2T4+716S4kKxcNJah6uZn/qUyPCskIUj9IqtXD3KGNTM04wgO9wsNWlJDfoZVPiNyTbJDIY9T7SygxJa8xh41c337AVkh/YBiCMFujCmd2kM7OAm3rWGMG76S6QLpNwKcgn9BGshHqnd67eNrPQJ05as+bXhonQOe5AEfIWrZbSdBedrGrxA8TElcHRVRF5bDkPGOARIvPIzMTj1zZ/ly2s4w5V/1/o+TwFjjTPqamLqmnNGfXh2jmMIxnyVoCDWe7EZEoKEUafDAb5++Ttp/jRrp+wkAYzLPG3/9Ou7ppLYyAL2q9Jy7GSLjR1rGF5sW/rZjWnwqphprGVv8XsEfk0vDUW9SayW2XG7LO1bkcdPgRINBx0QE8hC8LsYqvX1umhFpTI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
